<package format="2">
  <name>human_retargeting_controller</name>
  <version>0.1.0</version>
  <description>
    Controller for retargeting the motion from human to humanoid robot
  </description>
  <maintainer email="m-murooka@aist.go.jp">Masaki Murooka</maintainer>
  <license>BSD</license>

  <url>http://ros.org/wiki/human_retargeting_controller</url>
  <author>Masaki Murooka</author>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>baseline_walking_controller</depend>

  <build_depend>eigen</build_depend>

  <exec_depend>rviz</exec_depend>
  <exec_depend>rospy</exec_depend>

  <doc_depend>doxygen</doc_depend>

  # added by selim 2026-03-13 based on hugo's last commit
  <buildtool_depend>ament_cmake</buildtool_depend>.
  <build_depend>ament_cmake_python</build_depend>
  
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  
  <exec_depend>tf_transformations</exec_depend>
  #######################################################

</package>
